@startuml
usecase (Use Case View) as UC0
rectangle Development {
  usecase UC1 as "Every Item will have
the attributes:
name, id, price, and warehouse
warehouse will have attributes:
name and items"
}
rectangle Process {
  usecase UC2 as "Items will be able to change: 
warehouse, price
warehouse will be able to:
add, remove, and view them"
}
rectangle Logical {
  usecase UC3 as "There will be an items class a warehouse class and
    warehouses class as well as a CLI for user interaction between them"
}
rectangle Physical {
  usecase UC4 as "Program will be implemented in Python"
}
UC0 -left-> Development
UC0 -right-> Process
UC0 -up-> Logical
UC0 -down-> Physical
@enduml